import React, { useState, useRef } from 'react';
import {
  GitBranch,
  Github,
  Upload,
  Sparkles,
  Check,
  Cpu,
  Layers,
  ArrowRight,
  Plus,
  Trash2,
  Code2,
  Zap,
  CheckCircle2,
  RefreshCw,
  FolderGit2,
  Globe,
  Database,
  Shield,
  Bot,
  FileArchive,
  FileCode,
  FileText
} from 'lucide-react';
import { ImportedRepository, DetectedTech, SpecKitProject, FeatureSpec, ImplementationPlan, TaskBreakdown, ProjectConstitution } from '../../types/speckit';
import { importSpecKitZip } from '../../lib/export';

interface RepoImportStudioProps {
  onImportComplete: (project: SpecKitProject) => void;
  isDarkMode?: boolean;
}

export const RepoImportStudio: React.FC<RepoImportStudioProps> = ({
  onImportComplete,
  isDarkMode = true,
}) => {
  const [importMode, setImportMode] = useState<'preset' | 'url' | 'paste' | 'zip'>('preset');
  const [githubUrl, setGithubUrl] = useState('');
  const [pastedManifest, setPastedManifest] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analyzedRepo, setAnalyzedRepo] = useState<ImportedRepository | null>(null);
  const [zipError, setZipError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // New Feature Development Form State
  const [newFeatureTitle, setNewFeatureTitle] = useState('');
  const [newFeatureGoal, setNewFeatureGoal] = useState('');
  const [isGeneratingFeatureSpec, setIsGeneratingFeatureSpec] = useState(false);
  const [customTechInput, setCustomTechInput] = useState('');

  // Sample Preset Repositories for instant testing
  const samplePresets = [
    {
      name: 'Next.js 15 Full-Stack SaaS',
      url: 'https://github.com/vercel/next.js',
      lang: 'TypeScript',
      desc: 'Modern full-stack App Router codebase with React 19, Server Actions, Prisma ORM, PostgreSQL, and Tailwind v4.',
      manifest: `{
  "name": "nextjs-saas-starter",
  "dependencies": {
    "next": "^15.1.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "@prisma/client": "^6.0.0",
    "@tanstack/react-query": "^5.60.0",
    "tailwindcss": "^4.0.0",
    "lucide-react": "^0.460.0",
    "zod": "^3.23.0"
  },
  "devDependencies": {
    "prisma": "^6.0.0",
    "typescript": "^5.7.0"
  }
}`
    },
    {
      name: 'Python FastAPI Microservice',
      url: 'https://github.com/fastapi/fastapi',
      lang: 'Python',
      desc: 'High performance async REST API backend using FastAPI, Pydantic, SQLAlchemy 2.0, PostgreSQL, and Redis.',
      manifest: `[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = "^0.32.0"
pydantic = "^2.9.0"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
redis = "^5.0.0"
celery = "^5.4.0"`
    },
    {
      name: 'Rust Actix-Web High-Throughput Engine',
      url: 'https://github.com/actix/actix-web',
      lang: 'Rust',
      desc: 'Ultra-fast asynchronous API engine in Rust with Actix-web, Diesel ORM, PostgreSQL, and Tokio.',
      manifest: `[package]
name = "rust-actix-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.2", features = ["postgres", "r2d2"] }
tracing = "0.1"`
    },
    {
      name: 'Go Fiber Microservice',
      url: 'https://github.com/gofiber/fiber',
      lang: 'Go',
      desc: 'Lightweight, Express-inspired Go backend service with Fiber v2, GORM, and PostgreSQL.',
      manifest: `module my-go-service

go 1.22

require (
	github.com/gofiber/fiber/v2 v2.52.5
	gorm.io/gorm v1.25.12
	gorm.io/driver/postgres v1.5.9
	github.com/redis/go-redis/v9 v9.6.1
)`
    }
  ];

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setZipError(null);
    setIsAnalyzing(true);
    try {
      if (file.name.endsWith('.zip')) {
        const importedProject = await importSpecKitZip(file);
        onImportComplete(importedProject as SpecKitProject);
      } else if (file.name.endsWith('.json')) {
        const text = await file.text();
        const json = JSON.parse(text);
        if (json.spec && json.plan) {
          onImportComplete(json as SpecKitProject);
        } else {
          throw new Error('JSON file must be a valid Spec-Kit project schema.');
        }
      } else {
        throw new Error('Please upload a .zip file generated by Spec-Kit or a .json Spec-Kit workspace file.');
      }
    } catch (err: any) {
      console.error('Failed to parse uploaded Spec-Kit package:', err);
      setZipError(err.message || 'Failed to parse Spec-Kit package file.');
    } finally {
      setIsAnalyzing(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleAnalyze = async (overrideManifest?: string, overrideUrl?: string) => {
    setIsAnalyzing(true);
    try {
      const manifestToSend = overrideManifest || pastedManifest;
      const urlToSend = overrideUrl || githubUrl;

      const res = await fetch('/api/repo/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repoUrl: urlToSend,
          manifestContent: manifestToSend,
        }),
      });

      const data = await res.json();
      if (data.success && data.data) {
        const repoData: ImportedRepository = {
          repoUrl: urlToSend || 'https://github.com/imported-project/repo',
          repoName: data.data.repoName || 'Imported Codebase',
          description: data.data.description || 'Imported repository for feature extension.',
          primaryLanguage: data.data.primaryLanguage || 'TypeScript',
          detectedTechStack: (data.data.detectedTechStack || []).map((t: any, index: number) => ({
            id: `TECH-${index + 1}`,
            category: t.category || 'Other',
            name: t.name || 'Technology',
            version: t.version || '',
            confidence: t.confidence || 'High',
            fileEvidence: t.fileEvidence || 'Manifest file',
            selectedForNewFeature: true,
          })),
          architectureSummary: data.data.architectureSummary || 'Standard layered architecture.',
          keyDirectories: data.data.keyDirectories || ['/src', '/api', '/components'],
          suggestedNewFeatures: data.data.suggestedNewFeatures || [
            'Add Role-Based Access Control (RBAC) & OAuth 2.0',
            'Add Real-time WebSockets Live Notifications',
            'Add AI Model Integration & Vector Search',
            'Add Stripe Billing & Subscription Management',
          ],
          importedAt: new Date().toISOString(),
        };

        setAnalyzedRepo(repoData);
        if (repoData.suggestedNewFeatures.length > 0) {
          setNewFeatureTitle(repoData.suggestedNewFeatures[0]);
          setNewFeatureGoal(`Add ${repoData.suggestedNewFeatures[0]} extending the existing ${repoData.repoName} codebase architecture.`);
        }
      }
    } catch (err) {
      console.error('Failed to analyze repository:', err);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleToggleTechSelection = (techId: string) => {
    if (!analyzedRepo) return;
    const updatedTech = analyzedRepo.detectedTechStack.map((t) =>
      t.id === techId ? { ...t, selectedForNewFeature: !t.selectedForNewFeature } : t
    );
    setAnalyzedRepo({ ...analyzedRepo, detectedTechStack: updatedTech });
  };

  const handleAddCustomTech = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customTechInput.trim() || !analyzedRepo) return;

    const newTech: DetectedTech = {
      id: `TECH-CUSTOM-${Date.now()}`,
      category: 'Other',
      name: customTechInput.trim(),
      confidence: 'High',
      fileEvidence: 'Added by developer',
      selectedForNewFeature: true,
    };

    setAnalyzedRepo({
      ...analyzedRepo,
      detectedTechStack: [...analyzedRepo.detectedTechStack, newTech],
    });
    setCustomTechInput('');
  };

  const handleGenerateFeatureSpecPackage = async () => {
    if (!analyzedRepo || !newFeatureTitle.trim()) return;

    setIsGeneratingFeatureSpec(true);
    try {
      const selectedTechStack = analyzedRepo.detectedTechStack.filter((t) => t.selectedForNewFeature);

      const res = await fetch('/api/repo/generate-feature-for-imported', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          importedRepo: analyzedRepo,
          selectedTechStack,
          newFeatureTitle,
          newFeatureGoal,
        }),
      });

      const result = await res.json();
      if (result.success && result.data) {
        const d = result.data;

        // Construct complete SpecKitProject
        const newSpec: FeatureSpec = {
          id: `SPEC-${Date.now()}`,
          title: d.title || newFeatureTitle,
          summary: d.summary || newFeatureGoal,
          userStories: d.userStories || [],
          functionalRequirements: d.functionalRequirements || [],
          nonFunctionalRequirements: [],
          userFlows: [],
          edgeCases: [],
          successMetrics: [],
          markdown: `# Feature Specification: ${d.title}\n\n${d.summary}`,
          lastUpdated: new Date().toISOString(),
        };

        const newPlan: ImplementationPlan = {
          id: `PLAN-${Date.now()}`,
          techStack: d.techStack || selectedTechStack.map((st) => ({
            category: st.category,
            technology: st.name,
            justification: `Selected from imported codebase ${analyzedRepo.repoName}`,
          })),
          architectureSummary: `Feature extension built on top of ${analyzedRepo.repoName} (${analyzedRepo.primaryLanguage}).`,
          components: [],
          apiContracts: d.apiContracts || [],
          dataSchemas: [],
          adrs: [
            {
              id: 'ADR-201',
              title: `Use ${selectedTechStack.map((s) => s.name).slice(0, 3).join(', ')} for ${newFeatureTitle}`,
              status: 'Accepted',
              context: `Adding new feature into imported repo ${analyzedRepo.repoName}`,
              decision: `Align feature implementation directly with ${analyzedRepo.primaryLanguage} and detected tech stack.`,
              consequences: 'Ensures zero architectural mismatch and seamless integration with existing codebase.',
              date: new Date().toISOString().split('T')[0],
            },
          ],
          mermaidDiagram: d.mermaidDiagram || `graph TD\n    A[Imported Repo: ${analyzedRepo.repoName}] --> B[New Feature: ${d.title}]\n    B --> C[Selected Tech Stack: ${selectedTechStack.map(s=>s.name).join(', ')}]`,
          markdown: `# Architecture Plan for ${d.title}`,
          lastUpdated: new Date().toISOString(),
        };

        const newTasks: TaskBreakdown = {
          id: `TASKS-${Date.now()}`,
          tasks: (d.tasks || []).map((t: any, idx: number) => ({
            id: t.id || `TASK-${200 + idx}`,
            title: t.title || 'Implementation task',
            phase: t.phase || 'Phase 1: Setup',
            description: t.description || 'Task description',
            status: 'todo',
            estimatedHours: t.estimatedHours || 3,
            mappedRequirementId: t.mappedRequirementId || 'FR-1',
            dependencies: [],
            targetAgentPromptSnippet: `Implement ${t.title} for feature ${d.title} in repository ${analyzedRepo.repoName}.`,
          })),
          markdown: `# Task Breakdown for ${d.title}`,
          lastUpdated: new Date().toISOString(),
        };

        const newConstitution: ProjectConstitution = {
          id: `CONST-${Date.now()}`,
          title: `${analyzedRepo.repoName} Governance Constitution`,
          rules: (d.constitutionRules || []).map((r: any, idx: number) => ({
            id: r.id || `RULE-${idx + 1}`,
            title: r.title || 'Rule',
            category: r.category || 'Architecture',
            description: r.description || 'Rule description',
            ruleStatement: r.ruleStatement || 'Statement',
            strictness: r.strictness || 'Mandatory',
          })),
          markdown: `# Constitution for ${analyzedRepo.repoName}`,
          lastUpdated: new Date().toISOString(),
        };

        const completeProject: SpecKitProject = {
          id: `PROJ-${Date.now()}`,
          name: `${analyzedRepo.repoName}: ${d.title}`,
          description: `Feature extension specification for ${analyzedRepo.repoName} using ${selectedTechStack.map((s) => s.name).join(', ')}.`,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          spec: newSpec,
          plan: newPlan,
          tasks: newTasks,
          constitution: newConstitution,
          importedRepo: analyzedRepo,
          version: '1.0.0',
        };

        onImportComplete(completeProject);
      }
    } catch (err) {
      console.error('Failed to generate feature spec package for imported repo:', err);
    } finally {
      setIsGeneratingFeatureSpec(false);
    }
  };

  return (
    <div className="space-y-6 pb-12 max-w-6xl mx-auto">
      {/* Header Bar */}
      <div className="p-6 rounded-2xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-2.5">
            <div className="p-2 rounded-xl bg-sky-50 dark:bg-zinc-950 border border-sky-200 dark:border-zinc-800 text-sky-600 dark:text-cyan-400 shrink-0">
              <FolderGit2 className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              Import Existing Project / GitHub Repository
            </h2>
            <span className="text-[10px] uppercase tracking-wider font-extrabold px-2.5 py-0.5 rounded-full bg-sky-100 dark:bg-cyan-500/10 text-sky-800 dark:text-cyan-400 border border-sky-300 dark:border-cyan-500/30">
              Universal Tech Stack AI Parser
            </span>
          </div>
          <p className="text-xs text-slate-600 dark:text-zinc-300 mt-2 max-w-2xl leading-relaxed">
            Import any existing repository (Node.js, Python, Rust, Go, Java, Docker, etc.). Spec-Kit Studio automatically extracts all technologies used, lets you pick technology choices, and generates feature specifications and plans matched to the codebase!
          </p>
        </div>
      </div>

      {/* Step 1: Repository Input Options */}
      {!analyzedRepo ? (
        <div className="space-y-6">
          {/* Input Mode Selector */}
          <div className="p-1 rounded-xl bg-zinc-950 border border-zinc-800 flex flex-wrap items-center text-xs">
            <button
              onClick={() => setImportMode('preset')}
              className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-1.5 ${
                importMode === 'preset' ? 'bg-zinc-800 text-cyan-300 shadow-xs' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <Zap className="w-3.5 h-3.5 text-amber-400" />
              <span>Preset Repos</span>
            </button>
            <button
              onClick={() => setImportMode('url')}
              className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-1.5 ${
                importMode === 'url' ? 'bg-zinc-800 text-cyan-300 shadow-xs' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <Github className="w-3.5 h-3.5" />
              <span>GitHub URL</span>
            </button>
            <button
              onClick={() => setImportMode('paste')}
              className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-1.5 ${
                importMode === 'paste' ? 'bg-zinc-800 text-cyan-300 shadow-xs' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <Upload className="w-3.5 h-3.5" />
              <span>Paste Code</span>
            </button>
            <button
              onClick={() => setImportMode('zip')}
              className={`flex-1 py-2 px-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-1.5 ${
                importMode === 'zip' ? 'bg-zinc-800 text-purple-300 shadow-xs' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <FileArchive className="w-3.5 h-3.5 text-purple-400" />
              <span>Spec-Kit Package (.zip/.json)</span>
            </button>
          </div>

          {/* Mode 1: Preset Real-World Repos */}
          {importMode === 'preset' && (
            <div className="space-y-3">
              <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">
                Select a Real-World Repository Architecture to Test
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {samplePresets.map((preset) => (
                  <div
                    key={preset.name}
                    className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 hover:border-cyan-500/40 transition-all space-y-3 flex flex-col justify-between group"
                  >
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-sm text-zinc-100 group-hover:text-cyan-300 transition-colors">
                          {preset.name}
                        </span>
                        <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
                          {preset.lang}
                        </span>
                      </div>
                      <p className="text-xs text-zinc-400">{preset.desc}</p>
                    </div>

                    <button
                      onClick={() => handleAnalyze(preset.manifest, preset.url)}
                      disabled={isAnalyzing}
                      className="w-full py-2.5 rounded-xl bg-zinc-950 hover:bg-zinc-800 border border-zinc-800 text-xs font-semibold text-zinc-200 hover:text-cyan-300 flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Analyze Technologies & Import</span>
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Mode 2: GitHub Repository URL */}
          {importMode === 'url' && (
            <div className="p-6 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-4 text-xs">
              <div className="space-y-1">
                <label className="block font-bold text-zinc-100">GitHub Repository URL or Owner/Repo Slug</label>
                <p className="text-zinc-400">
                  Enter any public GitHub repository (e.g. <code>https://github.com/facebook/react</code>, <code>shadcn-ui/ui</code>, <code>fastapi/fastapi</code>).
                </p>
              </div>

              <div className="flex flex-col sm:flex-row gap-2">
                <input
                  type="text"
                  placeholder="https://github.com/owner/repository"
                  value={githubUrl}
                  onChange={(e) => setGithubUrl(e.target.value)}
                  className="flex-1 p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 focus:outline-none focus:border-cyan-500/50"
                />
                <button
                  onClick={() => handleAnalyze()}
                  disabled={isAnalyzing || !githubUrl.trim()}
                  className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold flex items-center justify-center gap-2 transition-all disabled:opacity-50 shrink-0"
                >
                  {isAnalyzing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                  <span>{isAnalyzing ? 'Analyzing Repository...' : 'Analyze Repository'}</span>
                </button>
              </div>
            </div>
          )}

          {/* Mode 3: Paste Manifest / Code */}
          {importMode === 'paste' && (
            <div className="p-6 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-4 text-xs">
              <div className="space-y-1">
                <label className="block font-bold text-zinc-100">Paste Manifest File, Dockerfile or File Tree</label>
                <p className="text-zinc-400">
                  Paste the contents of <code>package.json</code>, <code>requirements.txt</code>, <code>Cargo.toml</code>, <code>go.mod</code>, <code>pom.xml</code>, <code>schema.prisma</code>, or directory list.
                </p>
              </div>

              <textarea
                rows={10}
                placeholder={`Paste manifest contents here... e.g.
{
  "name": "my-custom-project",
  "dependencies": {
    "express": "^4.21.0",
    "pg": "^8.13.0",
    "react": "^19.0.0"
  }
}`}
                value={pastedManifest}
                onChange={(e) => setPastedManifest(e.target.value)}
                className="w-full p-4 rounded-xl bg-zinc-950 border border-zinc-800 text-cyan-300 font-mono focus:outline-none"
              />

              <button
                onClick={() => handleAnalyze()}
                disabled={isAnalyzing || !pastedManifest.trim()}
                className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold flex items-center gap-2 transition-all disabled:opacity-50"
              >
                {isAnalyzing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                <span>{isAnalyzing ? 'Analyzing Tech Stack...' : 'Analyze Manifest & Code'}</span>
              </button>
            </div>
          )}

          {/* Mode 4: Upload Spec-Kit Package ZIP / JSON */}
          {importMode === 'zip' && (
            <div className="p-8 rounded-2xl bg-zinc-900/60 border border-zinc-800/80 space-y-5 text-xs text-center flex flex-col items-center justify-center">
              <div className="w-12 h-12 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
                <FileArchive className="w-6 h-6" />
              </div>

              <div className="space-y-1.5 max-w-lg">
                <h3 className="text-base font-bold text-zinc-100">Upload Spec-Kit Package (.zip or .json)</h3>
                <p className="text-zinc-400 leading-relaxed">
                  Import a complete Spec-Kit archive or project exported from the CLI or Studio. All specs, implementation plans, task breakdowns, and constitution rules will be re-hydrated instantly into your workspace!
                </p>
              </div>

              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileUpload}
                accept=".zip,.json"
                className="hidden"
              />

              {zipError && (
                <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-300 font-semibold text-xs">
                  {zipError}
                </div>
              )}

              <button
                onClick={() => fileInputRef.current?.click()}
                disabled={isAnalyzing}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold flex items-center gap-2 shadow-lg shadow-purple-600/20 transition-all disabled:opacity-50"
              >
                {isAnalyzing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}
                <span>{isAnalyzing ? 'Extracting & Parsing Spec Package...' : 'Select Spec-Kit File (.zip / .json)'}</span>
              </button>
            </div>
          )}
        </div>
      ) : (
        /* Step 2: Interactive Technology Selection & New Feature Specification Studio */
        <div className="space-y-6">
          {/* Project Summary Banner */}
          <div className="p-5 rounded-2xl bg-zinc-900/80 border border-zinc-800 flex flex-col md:flex-row md:items-center justify-between gap-4 text-xs">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <Github className="w-4 h-4 text-cyan-400" />
                <h3 className="text-base font-bold text-zinc-100">{analyzedRepo.repoName}</h3>
                <span className="px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-300 font-mono font-bold border border-cyan-500/20 text-[10px]">
                  {analyzedRepo.primaryLanguage}
                </span>
              </div>
              <p className="text-zinc-400">{analyzedRepo.description}</p>
              <div className="text-[11px] text-zinc-500">
                <strong>Architecture Summary:</strong> {analyzedRepo.architectureSummary}
              </div>
            </div>

            <button
              onClick={() => setAnalyzedRepo(null)}
              className="px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-300 font-medium self-start md:self-auto shrink-0"
            >
              Re-Import / Change Repo
            </button>
          </div>

          {/* Interactive Technology Selection Grid */}
          <div className="p-6 rounded-2xl bg-zinc-900/60 border border-zinc-800 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold text-zinc-100 flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-cyan-400" />
                  <span>Detected Technology Stack ({analyzedRepo.detectedTechStack.length})</span>
                </h3>
                <p className="text-xs text-zinc-400 mt-0.5">
                  Select which technologies from the imported codebase should be used for building the new feature.
                </p>
              </div>

              <span className="text-xs text-emerald-400 font-bold">
                {analyzedRepo.detectedTechStack.filter((t) => t.selectedForNewFeature).length} Selected for New Feature
              </span>
            </div>

            {/* Tech Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {analyzedRepo.detectedTechStack.map((tech) => (
                <div
                  key={tech.id}
                  onClick={() => handleToggleTechSelection(tech.id)}
                  className={`p-3.5 rounded-xl border cursor-pointer transition-all text-xs space-y-1.5 ${
                    tech.selectedForNewFeature
                      ? 'bg-zinc-950 border-cyan-500/50 shadow-sm shadow-cyan-500/10'
                      : 'bg-zinc-950/40 border-zinc-800/80 opacity-60 hover:opacity-100'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-extrabold uppercase text-cyan-400 tracking-wider">
                      {tech.category}
                    </span>
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] px-1.5 py-0.2 rounded bg-zinc-800 text-zinc-400 font-mono">
                        {tech.fileEvidence}
                      </span>
                      <div
                        className={`w-4 h-4 rounded flex items-center justify-center text-white ${
                          tech.selectedForNewFeature ? 'bg-cyan-500' : 'bg-zinc-800'
                        }`}
                      >
                        {tech.selectedForNewFeature && <Check className="w-3 h-3" />}
                      </div>
                    </div>
                  </div>

                  <div className="font-bold text-zinc-100 text-sm">{tech.name}</div>
                  {tech.version && <div className="text-[10px] text-zinc-400 font-mono">Version: {tech.version}</div>}
                </div>
              ))}
            </div>

            {/* Add Custom Tech Form */}
            <form onSubmit={handleAddCustomTech} className="pt-2 flex items-center gap-2 text-xs">
              <input
                type="text"
                placeholder="Add custom technology to use for new feature (e.g. Redis, WebSockets, TanStack Query)..."
                value={customTechInput}
                onChange={(e) => setCustomTechInput(e.target.value)}
                className="flex-1 p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 focus:outline-none"
              />
              <button
                type="submit"
                className="px-4 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white font-semibold flex items-center gap-1"
              >
                <Plus className="w-4 h-4" />
                <span>Add Technology</span>
              </button>
            </form>
          </div>

          {/* New Feature Specification & Goal Form */}
          <div className="p-6 rounded-2xl bg-zinc-900/60 border border-zinc-800 space-y-4 text-xs">
            <h3 className="text-sm font-bold text-zinc-100 flex items-center gap-2">
              <Bot className="w-4 h-4 text-purple-400" />
              <span>Define New Feature to Build on Imported Codebase</span>
            </h3>

            <div className="space-y-3">
              <div>
                <label className="block font-semibold text-zinc-300 mb-1">New Feature Title</label>
                <input
                  type="text"
                  placeholder="e.g. Add Real-Time Collaborative Canvas Comments & WebSockets"
                  value={newFeatureTitle}
                  onChange={(e) => setNewFeatureTitle(e.target.value)}
                  className="w-full p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 focus:outline-none"
                />
              </div>

              {/* Quick Feature Suggestions Chips */}
              {analyzedRepo.suggestedNewFeatures.length > 0 && (
                <div className="space-y-1.5">
                  <div className="text-[11px] text-zinc-400 font-semibold">Suggested Features for this Codebase:</div>
                  <div className="flex flex-wrap gap-1.5">
                    {analyzedRepo.suggestedNewFeatures.map((feat, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => {
                          setNewFeatureTitle(feat);
                          setNewFeatureGoal(`Implement ${feat} extending the existing ${analyzedRepo.repoName} architecture.`);
                        }}
                        className="px-2.5 py-1 rounded-lg bg-purple-500/10 hover:bg-purple-500/20 text-purple-300 border border-purple-500/30 text-[11px] transition-colors"
                      >
                        + {feat}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <div>
                <label className="block font-semibold text-zinc-300 mb-1">Feature Scope & Architectural Goals</label>
                <textarea
                  rows={3}
                  placeholder="Describe what the new feature should do, which endpoints it should touch, and how it integrates into the existing codebase..."
                  value={newFeatureGoal}
                  onChange={(e) => setNewFeatureGoal(e.target.value)}
                  className="w-full p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 focus:outline-none"
                />
              </div>
            </div>

            {/* Action Trigger */}
            <button
              onClick={handleGenerateFeatureSpecPackage}
              disabled={isGeneratingFeatureSpec || !newFeatureTitle.trim()}
              className="w-full py-3.5 rounded-xl bg-gradient-to-r from-purple-600 via-indigo-600 to-cyan-600 hover:from-purple-500 hover:to-cyan-500 text-white font-bold text-sm flex items-center justify-center gap-2 shadow-xl shadow-purple-600/20 transition-all disabled:opacity-50"
            >
              {isGeneratingFeatureSpec ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              <span>
                {isGeneratingFeatureSpec
                  ? 'Generating Spec, Architecture Plan & Tasks for Imported Codebase...'
                  : 'Generate Spec-Kit Package for Selected Technologies'}
              </span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
