import React, { useMemo, useState } from 'react';
import { Bug, CheckCircle2, Clipboard, Lightbulb, ShieldCheck } from 'lucide-react';
import { SpecKitProject, StudioProcessCase, StudioProcessKind } from '../../types/speckit';
import { approveProcessStep, createProcessCase, processDefinitions } from '../../lib/processCases';

interface Props { project: SpecKitProject; onSaveCases: (cases: StudioProcessCase[]) => void; onStartFeature: () => void; onSelectWorkflow: (workflow: 'feature' | StudioProcessKind) => void; }

export function ProcessStudio({ project, onSaveCases, onStartFeature, onSelectWorkflow }: Props) {
  const [kind, setKind] = useState<StudioProcessKind>(project.workflowFocus === 'assessment' ? 'assessment' : 'bug');
  const [mode, setMode] = useState<'feature' | StudioProcessKind>(project.workflowFocus || 'bug');
  const [title, setTitle] = useState(''); const [input, setInput] = useState(''); const [selectedId, setSelectedId] = useState<string | undefined>();
  const cases = project.processCases || [];
  const selected = useMemo(() => cases.find((item) => item.id === selectedId) || cases.at(-1), [cases, selectedId]);
  const definition = processDefinitions[kind];
  const start = () => { if (!title.trim() || !input.trim()) return; const item = createProcessCase(kind, title, input); onSaveCases([...cases, item]); setSelectedId(item.id); setTitle(''); setInput(''); };
  const copy = async (text: string) => { await navigator.clipboard?.writeText(text); };
  const approve = (verdict?: StudioProcessCase['verdict']) => { if (!selected) return; onSaveCases(cases.map((item) => item.id === selected.id ? approveProcessStep(item, verdict) : item)); };

  return <div className="mx-auto max-w-5xl space-y-6 pb-12">
    <section className="rounded-2xl border border-cyan-500/25 bg-gradient-to-br from-cyan-500/10 via-zinc-900 to-zinc-900 p-6">
      <p className="text-[10px] font-black uppercase tracking-[0.18em] text-cyan-300">Choose work, not a phase</p><h1 className="mt-2 text-2xl font-bold text-zinc-100">What are you trying to do?</h1>
      <p className="mt-2 max-w-2xl text-sm text-zinc-400">Each workflow keeps its own evidence and never changes the Feature Journey. Choose the smallest process that fits the outcome.</p>
      <div className="mt-5 grid gap-3 md:grid-cols-3">
        <button type="button" onClick={() => { setMode('feature'); onSelectWorkflow('feature'); }} className={`rounded-xl border p-4 text-left ${mode === 'feature' ? 'border-cyan-400/60 bg-cyan-500/10' : 'border-zinc-700 bg-zinc-950/60'}`}><ShieldCheck className="h-5 w-5 text-cyan-300" /><p className="mt-3 font-bold text-zinc-100">Build a feature</p><p className="mt-1 text-xs text-zinc-400">Specify, plan, implement, and hand off.</p></button>
        <button type="button" onClick={() => { setKind('bug'); setMode('bug'); onSelectWorkflow('bug'); }} className={`rounded-xl border p-4 text-left ${mode === 'bug' ? 'border-rose-400/60 bg-rose-500/10' : 'border-zinc-700 bg-zinc-950/60'}`}><Bug className="h-5 w-5 text-rose-300" /><p className="mt-3 font-bold text-zinc-100">Fix a bug</p><p className="mt-1 text-xs text-zinc-400">Assess → scoped fix → verify.</p></button>
        <button type="button" onClick={() => { setKind('assessment'); setMode('assessment'); onSelectWorkflow('assessment'); }} className={`rounded-xl border p-4 text-left ${mode === 'assessment' ? 'border-violet-400/60 bg-violet-500/10' : 'border-zinc-700 bg-zinc-950/60'}`}><Lightbulb className="h-5 w-5 text-violet-300" /><p className="mt-3 font-bold text-zinc-100">Assess an idea</p><p className="mt-1 text-xs text-zinc-400">Evidence first; decide go, clarify, or stop.</p></button>
      </div>
    </section>

    {mode === 'feature' ? <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><h2 className="font-bold text-zinc-100">Build a feature</h2><p className="mt-1 max-w-2xl text-xs leading-relaxed text-zinc-400">Use this when you know what needs to be built. Studio will collect a focused brief first, then guide it through specification, design, delivery, implementation, and handoff. It is separate from bug repair and idea assessment.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={onStartFeature} className="rounded-lg bg-cyan-400 px-4 py-2.5 text-xs font-bold text-zinc-950">Describe a new feature</button></div></section> : <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><h2 className="font-bold text-zinc-100">Start {definition.label.toLowerCase()}</h2><p className="mt-1 text-xs text-zinc-400">{definition.description}</p>
      <div className="mt-4 grid gap-3"><label className="text-xs text-zinc-300">Short name<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder={kind === 'bug' ? 'Login form crashes on empty password' : 'Offline mode for field users'} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-zinc-100" /></label><label className="text-xs text-zinc-300">{kind === 'bug' ? 'What happened, how to reproduce it, and what should happen instead' : 'What is the idea, who has the problem, and why it matters'}<textarea value={input} onChange={(e) => setInput(e.target.value)} rows={4} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-zinc-100" /></label></div>
      <button type="button" disabled={!title.trim() || !input.trim()} onClick={start} className="mt-4 rounded-lg bg-cyan-400 px-4 py-2.5 text-xs font-bold text-zinc-950 disabled:opacity-40">Create {kind === 'bug' ? 'bug case' : 'assessment'}</button>
    </section>}

    {selected && (() => { const flow = processDefinitions[selected.kind]; const step = flow.steps[selected.currentStep]; const done = selected.completedSteps.includes(selected.currentStep); return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-cyan-300">Active {selected.kind === 'bug' ? 'bug case' : 'assessment'}</p><h2 className="mt-1 text-lg font-bold text-zinc-100">{selected.title}</h2><p className="mt-1 font-mono text-xs text-zinc-500">{flow.root(selected.slug)}</p></div><span className="rounded-full border border-zinc-700 px-3 py-1 text-xs text-zinc-300">Step {selected.currentStep + 1} of {flow.steps.length}</span></div>
      <div className="mt-5 rounded-xl border border-cyan-400/25 bg-cyan-500/5 p-4"><p className="font-bold text-cyan-100">Next: {step.title}</p><p className="mt-1 text-xs text-zinc-400">Creates {step.artifact}. {step.writeScope === 'source-change' ? 'This is the only step allowed to edit source code; review the assessment first.' : 'This step must not edit source code.'}</p><pre className="mt-3 overflow-auto rounded-lg bg-zinc-950 p-3 text-xs text-cyan-200">{step.command(selected)}</pre><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => copy(step.command(selected))} className="inline-flex items-center gap-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-zinc-950"><Clipboard className="h-3.5 w-3.5" />Copy next engine step</button><button type="button" onClick={() => copy(flow.setup)} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs font-bold text-zinc-200">Copy one-time setup</button>{!done && <button type="button" onClick={() => approve()} className="rounded-lg border border-emerald-400/35 px-3 py-2 text-xs font-bold text-emerald-200">I reviewed {step.artifact}</button>}</div></div>
      {selected.kind === 'assessment' && selected.completedSteps.includes(flow.steps.length - 1) && <div className="mt-4 flex flex-wrap gap-2"><span className="self-center text-xs text-zinc-400">Decision after reviewing decision.md:</span>{(['go', 'needs-clarification', 'kill'] as const).map((verdict) => <button key={verdict} type="button" onClick={() => approve(verdict)} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs font-bold text-zinc-200">{verdict}</button>)}</div>}
      {selected.verdict === 'go' && <button type="button" onClick={onStartFeature} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-zinc-950"><CheckCircle2 className="h-3.5 w-3.5" />Start a feature from this decision</button>}
    </section>; })()}
  </div>;
}
