import React, { useMemo, useState } from 'react';
import { CheckCircle2, ChevronDown, CircleAlert, FileSearch, GitBranch, HardDrive, LoaderCircle, Sparkles, Terminal, XCircle } from 'lucide-react';
import { SpecKitProject } from '../../types/speckit';
import { ConnectorJob, connectorClient, TruthReport, ValidationResult, WorkspaceChange } from '../../lib/connector';
import { createWorkspaceFiles } from '../../lib/workspaceFiles';
import { EditorHeader } from '../common/EditorHeader';

interface Props { project: SpecKitProject; onTruthAttached: (report: TruthReport) => void; }
type BaselineResult = { label: string; ok: boolean; output: string };
const defaultUrl = localStorage.getItem('speckit_connector_url') || 'http://127.0.0.1:4318';
function explainError(raw: string) {
  if (/could not resolve host|http status:\s*000/i.test(raw)) return 'Homebrew cannot reach its download service because this Mac cannot resolve formulae.brew.sh. Check your internet connection, VPN, proxy, or DNS settings, then retry.';
  if (/spawn uv enoent/i.test(raw)) return 'uv is not installed or is not available to the local connector. Use the guided uv installation step, then retry.';
  if (/connector token is required/i.test(raw)) return 'This local connector requires a pairing token. Enter the matching token in Connection settings, then retry.';
  return raw || 'Something went wrong.';
}

function Step({ number, title, description, state, children }: { number: number; title: string; description: string; state: 'current' | 'complete' | 'pending'; children?: React.ReactNode }) {
  const tone = state === 'complete' ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' : state === 'current' ? 'bg-cyan-500/15 text-cyan-300 border-cyan-500/40' : 'bg-zinc-800 text-zinc-500 border-zinc-700';
  return <div className={`rounded-2xl border p-4 ${state === 'current' ? 'bg-zinc-900/80 border-cyan-500/25' : 'bg-zinc-900/40 border-zinc-800'} ${state === 'pending' ? 'opacity-60' : ''}`}><div className="flex gap-3"><div className={`h-7 w-7 shrink-0 rounded-full border flex items-center justify-center text-xs font-black ${tone}`}>{state === 'complete' ? <CheckCircle2 className="w-4 h-4" /> : number}</div><div className="min-w-0 flex-1"><h3 className="font-bold text-zinc-100">{title}</h3><p className="mt-1 text-zinc-400 leading-relaxed">{description}</p>{children && <div className="mt-3">{children}</div>}</div></div></div>;
}

export function WorkspaceControlCenter({ project, onTruthAttached }: Props) {
  const [baseUrl, setBaseUrl] = useState(defaultUrl); const [token, setToken] = useState(''); const [repositoryPath, setRepositoryPath] = useState('');
  const [integration, setIntegration] = useState('copilot'); const [truth, setTruth] = useState<TruthReport | null>(null); const [cliInstalled, setCliInstalled] = useState<boolean | null>(null); const [uvAvailable, setUvAvailable] = useState<boolean | null>(null);
  const [setupMessage, setSetupMessage] = useState('Choose a clean repository, then scan it.'); const [setupError, setSetupError] = useState(''); const [busyAction, setBusyAction] = useState<string | null>(null); const [connectionOpen, setConnectionOpen] = useState(false);
  const [baseline, setBaseline] = useState<BaselineResult[]>([]); const [ignoredBaselineChecks, setIgnoredBaselineChecks] = useState<string[]>([]); const [validation, setValidation] = useState<ValidationResult | null>(null); const [changes, setChanges] = useState<WorkspaceChange[]>([]); const [diagnostics, setDiagnostics] = useState(''); const [dependencyJob, setDependencyJob] = useState<ConnectorJob | null>(null); const [baselineJob, setBaselineJob] = useState<ConnectorJob | null>(null); const [baselineProgress, setBaselineProgress] = useState<{ current: number; total: number } | null>(null);
  const client = useMemo(() => connectorClient(baseUrl, token), [baseUrl, token]); const files = useMemo(() => createWorkspaceFiles(project), [project]); const ready = Boolean(truth?.specKit.detected); const isBusy = busyAction !== null;
  const action = async (name: string, work: () => Promise<void>) => { setBusyAction(name); setSetupError(''); try { await work(); } catch (error: any) { const raw = error.message || 'Something went wrong.'; setSetupError(explainError(raw)); setDiagnostics(`Technical detail:\n${raw}`); setConnectionOpen(true); } finally { setBusyAction(null); } };
  const inspectOfficial = async () => { setSetupMessage('Checking the official Spec-Kit CLI…'); const result = await client.specKitStatus(repositoryPath); setCliInstalled(result.installed); setUvAvailable(result.prerequisites.uvAvailable); setDiagnostics(result.installed ? `${result.version.output}\n${result.check?.output || ''}`.trim() : result.version.output); setSetupMessage(result.installed ? 'Official Spec-Kit is installed. You can initialize this fresh clone.' : !result.prerequisites.uvAvailable ? 'uv is needed before we can install official Spec-Kit.' : 'Official Spec-Kit needs to be installed on this machine.'); return result; };
  const scan = () => action('scan', async () => {
    localStorage.setItem('speckit_connector_url', baseUrl);
    const health = await client.health();
    if (health.tokenRequired && !token.trim()) {
      setSetupError('This local connector requires a pairing token before it can read any repository.');
      setSetupMessage('Enter your pairing token to continue.');
      setConnectionOpen(true);
      setDiagnostics('Pairing token required. Enter the value configured as STUDIO_CONNECTOR_TOKEN in the local connector, then scan again.');
      return;
    }
    setCliInstalled(null); setBaseline([]); setIgnoredBaselineChecks([]); setValidation(null); setChanges([]);
    const report = await client.scan(repositoryPath); localStorage.setItem('speckit_local_agents', JSON.stringify(report.agents)); setTruth(report); onTruthAttached(report); await inspectOfficial();
    const readyAgents = report.agents.filter((agent) => agent.installed).map((agent) => agent.label);
    setDiagnostics(`Scan completed: ${report.files.length}${report.filesTruncated ? '+' : ''} files, ${report.technologies.length} evidence-backed technology findings.\nLocal agents: ${readyAgents.length ? readyAgents.join(', ') : 'none detected — Gemini will be the default generation path.'}\n\n${report.git.status || 'Clean working tree'}`);
  });
  const install = () => { if (!window.confirm('Install the official specify-cli on this machine? This downloads a developer tool through uv. It will not change this repository.')) return; action('install', async () => { setSetupMessage('Installing official Spec-Kit. This can take a few minutes…'); const result = await client.installSpecKit(repositoryPath); if (!result.ok) throw new Error(result.output || 'Installation failed. Install uv, then try again.'); await inspectOfficial(); setSetupMessage('Installed. Choose your coding agent and initialize the clone.'); }); };
  const installUv = () => { if (!window.confirm('Install uv in Studio’s isolated tools environment? This does not modify Homebrew, system Python, or the target repository.')) return; action('install-uv', async () => { setSetupMessage('Creating Studio’s isolated tools environment and installing uv…'); const result = await client.installUv(repositoryPath); if (!result.ok) throw new Error(result.output || 'uv installation failed.'); await inspectOfficial(); setSetupMessage('uv is installed. The next step is installing official Spec-Kit.'); }); };
  const initialize = () => { if (!window.confirm(`Initialize official Spec-Kit for ${integration} in this fresh clone? This creates .specify/ and agent integration files.`)) return; action('initialize', async () => { setSetupMessage(`Creating the official ${integration} workspace…`); const result = await client.initializeSpecKit(repositoryPath, integration); if (!result.ok) throw new Error(result.output || 'Initialization failed.'); const report = await client.scan(repositoryPath); localStorage.setItem('speckit_local_agents', JSON.stringify(report.agents)); setTruth(report); onTruthAttached(report); await inspectOfficial(); setSetupMessage('Your repository is ready for a feature specification.'); setDiagnostics(result.output); }); };
  const runBaseline = () => action('baseline', async () => { if (!truth) return; if (!truth.baselineCommands.length) { setBaseline([]); setDiagnostics('No supported baseline commands were detected. Add a project command or select a component-specific workflow before continuing.'); return; } setIgnoredBaselineChecks([]); const results: BaselineResult[] = []; for (const [index, item] of truth.baselineCommands.entries()) { setBaselineProgress({ current: index + 1, total: truth.baselineCommands.length }); let job = await client.startBaseline(repositoryPath, item.id); setBaselineJob(job); while (job.status === 'running') { await new Promise((resolve) => window.setTimeout(resolve, 500)); job = await client.getJob(job.id); setBaselineJob(job); } results.push({ label: job.label, ok: Boolean(job.ok), output: job.output }); } setBaseline(results); setDiagnostics(results.map((result) => `${result.label}: ${result.ok ? 'passed' : 'failed'}\n${result.output}`).join('\n\n')); });
  const installDependencies = () => { if (!truth || !window.confirm('Install the declared frontend dependencies? Studio will run npm ci when the project has a lockfile. It writes node_modules but does not change source files.')) return; action('dependencies', async () => { const workspaces = [...new Set(truth.baselineCommands.map((item) => item.workingDirectory))]; const finished: ConnectorJob[] = []; for (const workspace of workspaces) { let job = await client.startDependencyInstall(repositoryPath, workspace); setDependencyJob(job); while (job.status === 'running') { await new Promise((resolve) => window.setTimeout(resolve, 500)); job = await client.getJob(job.id); setDependencyJob(job); } finished.push(job); if (!job.ok) throw new Error(job.output || `${job.command} failed.`); } setBaseline([]); setDiagnostics(`Dependencies installed for ${finished.map((job) => job.label).join(', ')}. Re-run the baseline health check.`); }); };
  const validate = () => action('validate', async () => { const result = await client.validate(project); setValidation(result); setDiagnostics(result.passed ? 'Studio traceability validation passed.' : result.errors.map((item) => item.message).join('\n')); });
  const preview = () => action('preview', async () => { const result = await client.preview(repositoryPath, files); setChanges(result.changes); setDiagnostics(`${result.changes.length} proposed Studio artifact changes. Nothing has been written.`); });
  const apply = () => { if (!changes.length || !window.confirm(`Write ${changes.length} reviewed Studio artifact(s) beneath .specify/studio/?`)) return; action('apply', async () => { const result = await client.apply(repositoryPath, files); setChanges([]); setDiagnostics(`Applied ${result.applied.length} Studio artifact(s).`); }); };
  const firstBaseline = baseline.length === 0; const blockingBaseline = baseline.filter((result) => !ignoredBaselineChecks.includes(result.label)); const baselinePassed = baseline.length > 0 && blockingBaseline.every((result) => result.ok); const dependenciesMissing = baseline.some((result) => /command not found|ERR_MODULE_NOT_FOUND|Could not resolve ['\"](?:vite|@vitejs)/i.test(result.output));

  const nextTitle = !truth ? 'Connect a repository' : !ready ? cliInstalled === false && uvAvailable === false ? 'Install uv first' : cliInstalled === false ? 'Install the official Spec-Kit CLI' : cliInstalled ? 'Initialize this fresh clone' : 'Checking your setup' : firstBaseline ? 'Establish a clean baseline' : baselinePassed ? 'Create your first feature specification' : 'Resolve the baseline checks';
  const nextDescription = !truth ? 'We will read the repository first. No files are changed during a scan.' : !ready ? setupMessage : firstBaseline ? 'Run the checks this repository already provides before planning feature work.' : baselinePassed ? 'Your repository and official workflow are ready. Define the feature next, then return here to validate and export it.' : 'At least one baseline check failed. Review its result before creating a feature.';

  return <div className="space-y-6 pb-12 max-w-5xl mx-auto">
    <EditorHeader icon={HardDrive} iconColor="text-cyan-400" title="Connected Workspace" subtitle="A calm, guided path from a local repository to a feature-ready workspace." badgeLabel={ready ? 'Workspace ready' : 'Guided setup'} badgeColor={ready ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' : 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20'} />
    <section className="rounded-2xl border border-cyan-500/20 bg-gradient-to-br from-cyan-500/10 via-zinc-900/80 to-zinc-900/60 p-5 md:p-6"><div className="flex flex-col md:flex-row gap-5 md:items-center md:justify-between"><div><div className="text-[10px] uppercase tracking-[0.18em] font-black text-cyan-400">Your next step</div><h2 className="mt-1 text-lg font-bold text-zinc-100">{nextTitle}</h2><p className="mt-1 text-sm text-zinc-400 max-w-2xl">{nextDescription}</p></div>{ready && <div className="shrink-0 rounded-xl bg-emerald-500/10 border border-emerald-500/20 px-4 py-3 text-center"><div className="text-2xl font-black text-emerald-400">{baselinePassed ? '✓' : '2/3'}</div><div className="text-[10px] text-emerald-300 uppercase tracking-wide font-bold">{baselinePassed ? 'Ready to plan' : 'Setup complete'}</div></div>}</div></section>
    <section className="space-y-3 text-xs">
      <Step number={1} title="Connect your repository" description="Use an absolute path to a clean clone. Scanning is read-only and automatically checks official Spec-Kit." state={truth ? 'complete' : 'current'}>
        {!truth && <div className="space-y-3"><label className="block font-semibold text-zinc-300">Repository path</label><input value={repositoryPath} onChange={(event) => setRepositoryPath(event.target.value)} placeholder="/absolute/path/to/repository" className="w-full p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100 focus:outline-none focus:border-cyan-500/60" />{setupError && <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-100"><div className="font-bold flex items-center gap-1.5"><CircleAlert className="w-4 h-4" />Couldn’t connect to the local connector</div><p className="mt-1">{setupError}</p><p className="mt-1 text-rose-300">{/token/i.test(setupError) ? 'Enter the matching pairing token in Connection settings below, then scan again.' : 'Open Connection settings below to check the connector URL, token, and allowed repository path.'}</p><button type="button" onClick={() => setConnectionOpen(true)} className="mt-2 text-rose-100 underline font-semibold">Open connection settings</button></div>}<button type="button" onClick={scan} disabled={isBusy || !repositoryPath} className="w-full sm:w-auto px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-zinc-950 font-bold disabled:opacity-50 flex items-center justify-center gap-2">{busyAction === 'scan' ? <LoaderCircle className="w-4 h-4 animate-spin" /> : <FileSearch className="w-4 h-4" />}{busyAction === 'scan' ? 'Reading repository…' : 'Scan repository'}</button></div>}
        {truth && <div className="space-y-2 text-[11px]"><div className="flex flex-wrap gap-2"><span className="px-2 py-1 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-300">{truth.repositoryName}</span><span className="px-2 py-1 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-400"><GitBranch className="inline w-3 h-3 mr-1" />{truth.git.branch || 'No Git branch'}</span><span className="px-2 py-1 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-400">{truth.technologies.length} technologies found</span></div><div className="flex flex-wrap items-center gap-2"><span className="text-zinc-500">Local agents:</span>{truth.agents.filter((agent) => agent.installed).length ? truth.agents.filter((agent) => agent.installed).map((agent) => <span key={agent.id} className="px-2 py-1 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-300">{agent.label} ready</span>) : <span className="px-2 py-1 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-200">None detected · Gemini will be used by default</span>}</div></div>}
      </Step>
      <Step number={2} title="Set up the official workflow" description="The tool presents only the safe next action for this repository." state={ready ? 'complete' : truth ? 'current' : 'pending'}>
        {truth && !ready && <div className="space-y-3">{setupError && <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-200"><div className="font-bold flex items-center gap-1.5"><CircleAlert className="w-4 h-4" />Setup needs attention</div><p className="mt-1">{setupError}</p></div>}{cliInstalled === null ? <div className="text-cyan-300 flex items-center gap-2"><LoaderCircle className="w-4 h-4 animate-spin" />Checking prerequisites…</div> : cliInstalled === false && uvAvailable === false ? <div className="space-y-2"><p className="text-zinc-300">This Mac needs <strong>uv</strong>, the small installer used by official Spec-Kit.</p><button type="button" onClick={installUv} disabled={isBusy} className="w-full sm:w-auto px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-zinc-950 font-bold disabled:opacity-50 flex items-center justify-center gap-2">{busyAction === 'install-uv' && <LoaderCircle className="w-4 h-4 animate-spin" />}{busyAction === 'install-uv' ? 'Installing uv…' : 'Install uv in Studio'}</button><p className="text-zinc-500">This uses an isolated Studio environment. It does not modify Homebrew, system Python, or this repository.</p></div> : cliInstalled === false ? <button type="button" onClick={install} disabled={isBusy} className="w-full sm:w-auto px-4 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-zinc-950 font-bold disabled:opacity-50 flex items-center gap-2">{busyAction === 'install' && <LoaderCircle className="w-4 h-4 animate-spin" />}{busyAction === 'install' ? 'Installing official Spec-Kit…' : 'Install official Spec-Kit'}</button> : <div className="max-w-md space-y-3"><label className="block font-semibold text-zinc-300">Coding-agent integration</label><select value={integration} onChange={(event) => setIntegration(event.target.value)} disabled={isBusy} className="w-full p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-100"><option value="copilot">GitHub Copilot</option><option value="claude">Claude Code</option><option value="gemini">Gemini CLI</option></select><button type="button" onClick={initialize} disabled={isBusy} className="w-full px-4 py-2.5 rounded-xl bg-amber-400 hover:bg-amber-300 text-zinc-950 font-bold disabled:opacity-50 flex items-center justify-center gap-2">{busyAction === 'initialize' && <LoaderCircle className="w-4 h-4 animate-spin" />}{busyAction === 'initialize' ? 'Initializing workspace…' : 'Initialize this clone'}</button><p className="text-zinc-500">You will confirm before any files are written.</p></div>}</div>}
        {ready && <p className="text-emerald-400 flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4" />Official Spec-Kit workspace detected.</p>}
      </Step>
      <Step number={3} title="Establish a baseline" description="Run only the checks already declared by this repository. This gives feature work a known-good starting point." state={baselinePassed ? 'complete' : ready ? 'current' : 'pending'}>
        {ready && !baselinePassed && <button type="button" onClick={runBaseline} disabled={isBusy} className="w-full sm:w-auto px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-zinc-950 font-bold disabled:opacity-50 flex items-center justify-center gap-2">{busyAction === 'baseline' && <LoaderCircle className="w-4 h-4 animate-spin" />}{busyAction === 'baseline' ? 'Running baseline checks…' : firstBaseline ? 'Run baseline health check' : 'Re-run baseline health check'}</button>}
        {baselineJob && <div className={`mt-3 rounded-xl border p-3 ${baselineJob.status === 'failed' ? 'border-rose-500/30 bg-rose-500/10' : baselineJob.status === 'succeeded' ? 'border-emerald-500/30 bg-emerald-500/10' : 'border-cyan-500/30 bg-zinc-950/60'}`}><div className="flex items-center justify-between gap-3"><div className="font-semibold flex items-center gap-2">{baselineJob.status === 'running' && <LoaderCircle className="w-4 h-4 animate-spin text-cyan-300" />}{baselineJob.status === 'succeeded' && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}{baselineJob.status === 'failed' && <XCircle className="w-4 h-4 text-rose-300" />}{baselineJob.status === 'running' ? `Running ${baselineJob.label}…` : baselineJob.ok ? `${baselineJob.label} passed` : `${baselineJob.label} failed`}</div>{baselineProgress && <span className="shrink-0 rounded-full bg-zinc-950/70 px-2 py-1 text-[10px] font-bold text-cyan-200">Check {baselineProgress.current} of {baselineProgress.total}</span>}</div><p className="mt-1 text-[11px] text-zinc-400">Running <code>{baselineJob.command}</code> · max 3 minutes per check</p><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded-md bg-zinc-950/80 p-2 text-[10px] text-zinc-300">{baselineJob.output || 'Command started; waiting for output…'}</pre></div>}
        {baseline.length > 0 && <div className="grid sm:grid-cols-3 gap-2">{baseline.map((result) => { const ignored = ignoredBaselineChecks.includes(result.label); return <div key={result.label} className={`p-3 rounded-xl border ${result.ok ? 'bg-emerald-500/10 border-emerald-500/25 text-emerald-300' : ignored ? 'bg-amber-500/10 border-amber-500/25 text-amber-100' : 'bg-rose-500/10 border-rose-500/25 text-rose-200'}`}><div className="font-bold flex gap-1.5 items-center">{result.ok ? <CheckCircle2 className="w-4 h-4" /> : ignored ? <CircleAlert className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}{result.label}</div>{!result.ok && <button type="button" onClick={() => setIgnoredBaselineChecks((current) => ignored ? current.filter((label) => label !== result.label) : [...current, result.label])} className="mt-2 text-[10px] underline font-semibold">{ignored ? 'Require this check again' : 'Ignore for now and continue'}</button>}{ignored && <p className="mt-1 text-[10px] text-amber-200">Acknowledged for this Studio session; the repository is unchanged.</p>}<details className="mt-2 text-[10px] text-zinc-400"><summary className="cursor-pointer">View result</summary><pre className="mt-2 whitespace-pre-wrap max-h-28 overflow-auto">{result.output || 'No output.'}</pre></details></div>; })}</div>}
        {dependenciesMissing && <div className="mt-3 p-3 rounded-xl bg-amber-500/10 border border-amber-500/25 text-amber-100"><p className="font-bold">Frontend dependencies are not installed.</p><p className="mt-1 text-amber-200">This fresh clone is missing its local packages, so lint, tests, and build cannot start yet. Studio will run <code>npm ci</code> from the committed lockfile.</p><button type="button" onClick={installDependencies} disabled={isBusy} className="mt-3 px-3 py-2 rounded-lg bg-amber-400 hover:bg-amber-300 text-zinc-950 font-bold disabled:opacity-50">{busyAction === 'dependencies' ? 'Installing frontend dependencies…' : 'Install frontend dependencies'}</button>{dependencyJob && <div className={`mt-3 rounded-lg border p-3 ${dependencyJob.status === 'failed' ? 'border-rose-500/30 bg-rose-500/10' : dependencyJob.status === 'succeeded' ? 'border-emerald-500/30 bg-emerald-500/10' : 'border-amber-400/30 bg-zinc-950/60'}`}><div className="flex items-center gap-2 font-semibold">{dependencyJob.status === 'running' && <LoaderCircle className="w-4 h-4 animate-spin" />}{dependencyJob.status === 'succeeded' && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}{dependencyJob.status === 'failed' && <XCircle className="w-4 h-4 text-rose-300" />}{dependencyJob.status === 'running' ? `Installing ${dependencyJob.label}…` : dependencyJob.ok ? `${dependencyJob.label} dependencies installed` : `${dependencyJob.label} installation failed`}</div><p className="mt-1 text-[11px] text-zinc-400">Running <code>{dependencyJob.command}</code></p><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded-md bg-zinc-950/80 p-2 text-[10px] text-zinc-300">{dependencyJob.output || 'Preparing installation…'}</pre></div>}</div>}
      </Step>
    </section>
    {ready && baselinePassed && <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5 text-xs"><div className="flex gap-3"><Sparkles className="w-5 h-5 text-purple-400 shrink-0" /><div><h2 className="font-bold text-zinc-100">Ready for feature work</h2><p className="mt-1 text-zinc-400 leading-relaxed">Create a feature spec from the left navigation. When it is ready, return here to validate traceability and preview the artifacts that will be added to the repository.</p></div></div><div className="mt-4 pt-4 border-t border-zinc-800 flex flex-wrap gap-2"><button type="button" onClick={validate} disabled={isBusy} className="px-3 py-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-zinc-100 font-semibold">Validate feature traceability</button><button type="button" onClick={preview} disabled={isBusy} className="px-3 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-semibold">Preview feature artifacts</button></div>{validation && <p className={`mt-3 ${validation.passed ? 'text-emerald-400' : 'text-rose-300'}`}>{validation.passed ? 'Traceability validation passed.' : validation.errors.map((item) => item.message).join(' · ')}</p>}{changes.length > 0 && <div className="mt-3 p-3 rounded-xl bg-zinc-950 border border-zinc-800"><p className="font-bold text-zinc-200">{changes.length} reviewed artifact changes</p><ul className="mt-2 space-y-1 text-zinc-400">{changes.map((change) => <li key={change.id}><span className="text-cyan-300">{change.operation}</span> {change.path}</li>)}</ul><button type="button" onClick={apply} disabled={isBusy} className="mt-3 px-3 py-2 rounded-lg bg-zinc-100 text-zinc-950 font-bold">Apply reviewed artifacts</button></div>}</section>}
    <details open={connectionOpen} onToggle={(event) => setConnectionOpen((event.target as HTMLDetailsElement).open)} className="rounded-2xl border border-zinc-800 bg-zinc-900/30 text-xs group"><summary className="cursor-pointer p-4 flex items-center justify-between text-zinc-400 hover:text-zinc-200"><span className="flex items-center gap-2"><Terminal className="w-4 h-4" />Connection settings & diagnostics</span><ChevronDown className="w-4 h-4 transition-transform group-open:rotate-180" /></summary><div className="border-t border-zinc-800 p-4 space-y-3"><p className="text-zinc-400">A pairing token is required only when <code>STUDIO_CONNECTOR_TOKEN</code> is configured for the connector. It must match exactly.</p><div className="grid md:grid-cols-2 gap-3"><label className="text-zinc-400">Connector URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} className="mt-1 w-full p-2.5 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-100" /></label><label className="text-zinc-400">Pairing token<input value={token} onChange={(event) => setToken(event.target.value)} type="password" placeholder="Enter only if your connector requires it" className="mt-1 w-full p-2.5 rounded-lg bg-zinc-950 border border-zinc-800 text-zinc-100" /></label></div><button type="button" onClick={() => action('recheck', async () => { await inspectOfficial(); })} disabled={isBusy || !repositoryPath} className="px-3 py-2 rounded-lg bg-zinc-800 border border-zinc-700 text-zinc-200 font-semibold">Re-check official setup</button>{diagnostics && <pre className="p-3 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-400 whitespace-pre-wrap max-h-56 overflow-auto">{diagnostics}</pre>}</div></details>
  </div>;
}
