import { Router } from 'express';

const githubHeaders = (token?: string) => ({ ...(token ? { Authorization: `Bearer ${token}` } : {}), Accept: 'application/vnd.github.v3+json', 'User-Agent': 'spec-kit-studio' });
const jiraCredentials = (body: any) => ({ domain: body.domain || process.env.JIRA_DOMAIN, email: body.email || process.env.JIRA_EMAIL, apiToken: body.apiToken || process.env.JIRA_API_TOKEN });
const jiraDomain = (domain: string) => domain.replace(/^https?:\/\//, '').replace(/\/$/, '');

export function createIntegrationRouter() {
  const router = Router();
  router.post('/api/github/repos', async (req, res) => {
    try { const token = req.body.token || process.env.GITHUB_TOKEN; if (!token) return res.status(400).json({ success: false, error: 'GitHub Personal Access Token is required.' }); const response = await fetch('https://api.github.com/user/repos?sort=updated&per_page=30', { headers: githubHeaders(token) }); if (!response.ok) throw new Error(`GitHub API error (${response.status}): ${await response.text()}`); const repos = await response.json(); res.json({ success: true, repos: repos.map((r: any) => ({ id: r.id, name: r.name, fullName: r.full_name, private: r.private, description: r.description, htmlUrl: r.html_url, defaultBranch: r.default_branch, language: r.language, updatedAt: r.updated_at })) }); } catch (error: any) { console.error('GitHub repos error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  router.post('/api/github/issues', async (req, res) => {
    try { const { token: requestToken, owner, repo } = req.body; const token = requestToken || process.env.GITHUB_TOKEN; if (!owner || !repo) return res.status(400).json({ success: false, error: 'Owner and Repo name are required.' }); const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=open&per_page=30`, { headers: githubHeaders(token) }); if (!response.ok) throw new Error(`GitHub API error (${response.status}): ${await response.text()}`); const issues = await response.json(); res.json({ success: true, issues: issues.map((issue: any) => ({ id: issue.id, number: issue.number, title: issue.title, body: issue.body, state: issue.state, htmlUrl: issue.html_url, labels: issue.labels.map((label: any) => label.name), user: issue.user?.login, createdAt: issue.created_at })) }); } catch (error: any) { console.error('GitHub issues error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  router.post('/api/github/commit-spec', async (req, res) => {
    try { const { token: requestToken, owner, repo, branch, files, commitMessage } = req.body; const token = requestToken || process.env.GITHUB_TOKEN; if (!token) return res.status(400).json({ success: false, error: 'GitHub PAT Token is required to commit files.' }); if (!owner || !repo || !files || typeof files !== 'object') return res.status(400).json({ success: false, error: 'Owner, Repo, and files object are required.' }); const targetBranch = branch || 'main'; const headers = githubHeaders(token); const results = []; for (const [filePath, content] of Object.entries(files)) { const pathInRepo = filePath.startsWith('.spec-kit/') ? filePath : `.spec-kit/${filePath}`; const current = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${pathInRepo}?ref=${targetBranch}`, { headers }); const existingSha = current.ok ? (await current.json()).sha : undefined; const body: any = { message: commitMessage || `docs(spec-kit): update ${pathInRepo} via Spec-Kit Studio`, content: Buffer.from(content as string).toString('base64'), branch: targetBranch, ...(existingSha ? { sha: existingSha } : {}) }; const put = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${pathInRepo}`, { method: 'PUT', headers, body: JSON.stringify(body) }); if (!put.ok) throw new Error(`Failed to commit ${pathInRepo}: ${await put.text()}`); const data = await put.json(); results.push({ path: pathInRepo, sha: data.content?.sha, htmlUrl: data.content?.html_url }); } res.json({ success: true, message: `Successfully committed ${results.length} files to ${owner}/${repo} (${targetBranch}).`, results }); } catch (error: any) { console.error('GitHub commit error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  router.post('/api/jira/projects', async (req, res) => {
    try { const { domain, email, apiToken } = jiraCredentials(req.body); if (!domain || !email || !apiToken) return res.status(400).json({ success: false, error: 'Jira Domain, Email, and API Token are required.' }); const normalized = jiraDomain(domain); const response = await fetch(`https://${normalized}/rest/api/3/project`, { headers: { Authorization: `Basic ${Buffer.from(`${email}:${apiToken}`).toString('base64')}`, Accept: 'application/json' } }); if (!response.ok) throw new Error(`Jira API error (${response.status}): ${await response.text()}`); const projects = await response.json(); res.json({ success: true, projects: projects.map((project: any) => ({ id: project.id, key: project.key, name: project.name, projectTypeKey: project.projectTypeKey, avatarUrl: project.avatarUrls?.['48x48'] })) }); } catch (error: any) { console.error('Jira projects error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  router.post('/api/jira/issues', async (req, res) => {
    try { const { projectKey } = req.body; const { domain, email, apiToken } = jiraCredentials(req.body); if (!domain || !email || !apiToken || !projectKey) return res.status(400).json({ success: false, error: 'Jira Domain, Email, API Token, and Project Key are required.' }); const normalized = jiraDomain(domain); const response = await fetch(`https://${normalized}/rest/api/3/search?jql=${encodeURIComponent(`project = "${projectKey}" ORDER BY updated DESC`)}&maxResults=30`, { headers: { Authorization: `Basic ${Buffer.from(`${email}:${apiToken}`).toString('base64')}`, Accept: 'application/json' } }); if (!response.ok) throw new Error(`Jira API error (${response.status}): ${await response.text()}`); const data = await response.json(); res.json({ success: true, issues: (data.issues || []).map((issue: any) => ({ id: issue.id, key: issue.key, summary: issue.fields.summary, descriptionText: issue.fields.description?.content?.[0]?.content?.[0]?.text || 'No description', status: issue.fields.status?.name, issueType: issue.fields.issuetype?.name, priority: issue.fields.priority?.name, assignee: issue.fields.assignee?.displayName, htmlUrl: `https://${normalized}/browse/${issue.key}` })) }); } catch (error: any) { console.error('Jira issues error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  router.post('/api/jira/create-issue', async (req, res) => {
    try { const { projectKey, issueType, summary, description } = req.body; const { domain, email, apiToken } = jiraCredentials(req.body); if (!domain || !email || !apiToken || !projectKey || !summary) return res.status(400).json({ success: false, error: 'Jira Domain, Email, API Token, Project Key, and Summary are required.' }); const normalized = jiraDomain(domain); const response = await fetch(`https://${normalized}/rest/api/3/issue`, { method: 'POST', headers: { Authorization: `Basic ${Buffer.from(`${email}:${apiToken}`).toString('base64')}`, 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ fields: { project: { key: projectKey }, summary, description: { type: 'doc', version: 1, content: [{ type: 'paragraph', content: [{ type: 'text', text: description || 'Created via Spec-Kit Studio' }] }] }, issuetype: { name: issueType || 'Story' } } }) }); if (!response.ok) throw new Error(`Jira Create Issue API error (${response.status}): ${await response.text()}`); const issue = await response.json(); res.json({ success: true, key: issue.key, id: issue.id, htmlUrl: `https://${normalized}/browse/${issue.key}` }); } catch (error: any) { console.error('Jira create issue error:', error); res.status(500).json({ success: false, error: error.message }); }
  });
  return router;
}
