import React from 'react';
import { AlertTriangle, FolderGit2, GitBranch, ShieldCheck } from 'lucide-react';
import { SpecKitProject } from '../../types/speckit';
import { buildFeatureRegistry } from '../../lib/featureRegistry';

export function FeatureRegistry({ project }: { project: SpecKitProject }) {
  const entries = buildFeatureRegistry(project);
  if (!entries.length) return null;
  return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5 text-xs"><div className="flex items-start gap-3"><div className="rounded-xl bg-cyan-500/10 p-2 text-cyan-300"><FolderGit2 className="h-5 w-5" /></div><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-cyan-300">Feature registry</p><h2 className="mt-1 font-bold text-zinc-100">Concurrent work at a glance</h2><p className="mt-1 text-zinc-400">Declared paths are compared only when feature owners provide them; no speculative conflict is shown.</p></div></div><div className="mt-4 space-y-2">{entries.map(({ feature, lifecycle, artifactRoot, conflicts }) => <article key={feature.id} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><div className="flex flex-wrap items-center gap-2"><strong className="text-zinc-100">{feature.featureKey || feature.title}</strong><span className="rounded bg-cyan-500/10 px-2 py-0.5 text-[10px] font-bold text-cyan-200">{lifecycle}</span><span className="ml-auto text-[10px] text-zinc-500">{feature.implementationReceipts?.length || 0} receipts</span></div><div className="mt-2 grid gap-1 text-[11px] text-zinc-400 sm:grid-cols-2"><span className="font-mono">{artifactRoot}</span><span className="flex items-center gap-1"><GitBranch className="h-3 w-3" />{feature.branch || 'No worktree branch yet'}</span></div>{conflicts.length > 0 ? <div className="mt-2 rounded-lg border border-amber-400/30 bg-amber-500/10 p-2 text-amber-100"><span className="flex items-center gap-1 font-bold"><AlertTriangle className="h-3.5 w-3.5" />Resolve before concurrent implementation</span>{conflicts.map((conflict) => <p key={conflict} className="mt-1 text-amber-200">{conflict}</p>)}</div> : <p className="mt-2 flex items-center gap-1 text-emerald-300"><ShieldCheck className="h-3.5 w-3.5" />No declared path conflict.</p>}</article>)}</div></section>;
}
