import React, { useMemo, useState } from 'react';
import { CheckCircle2, CheckSquare, Clock3, Code, Columns3, Table2 } from 'lucide-react';
import { FeatureDeliveryCompletionSource, FeatureDeliveryTask, featureDeliveryCompletionSource, parseFeatureDeliveryTasks } from '../../lib/featureDeliveryTasks';

interface Props { content: string; sourcePath?: string; completedTaskIds?: string[]; activeTaskId?: string | null; authorityLabel?: string; }

type DisplayTask = FeatureDeliveryTask & { completionSource: FeatureDeliveryCompletionSource; done: boolean };

/**
 * Renders the authoritative, feature-scoped Spec-Kit tasks.md. This is
 * intentionally separate from Studio's optional workspace task board: the
 * counts describe different things and must never be presented as substitutes.
 */
export function FeatureDeliveryBoard({ content, sourcePath, completedTaskIds = [], activeTaskId, authorityLabel }: Props) {
  const [view, setView] = useState<'kanban' | 'matrix' | 'source'>('kanban');
  const tasks = useMemo<DisplayTask[]>(() => parseFeatureDeliveryTasks(content).map((task) => {
    const completionSource = featureDeliveryCompletionSource(task, completedTaskIds);
    return { ...task, completionSource, done: completionSource !== 'planned' };
  }), [content, completedTaskIds]);
  const planCompletedCount = tasks.filter((task) => task.completionSource === 'tasks-md').length;
  const reviewedReceiptCount = tasks.filter((task) => task.completionSource === 'reviewed-receipt').length;
  const activeTasks = tasks.filter((task) => !task.done && task.id === activeTaskId);
  const columns = [
    { id: 'todo', label: 'To do', tasks: tasks.filter((task) => !task.done && task.id !== activeTaskId), icon: <span className="feature-delivery-board-dot h-2 w-2 rounded-full" /> },
    { id: 'active', label: 'In progress', tasks: activeTasks, icon: <span className="feature-delivery-board-dot h-2 w-2 rounded-full" /> },
    { id: 'complete', label: 'Completed', tasks: tasks.filter((task) => task.done), icon: <CheckCircle2 className="feature-delivery-board-icon h-3.5 w-3.5" /> },
  ];
  return <div className="feature-delivery-board mt-4 overflow-hidden rounded-2xl border">
    <div className="feature-delivery-board-header flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="feature-delivery-board-title flex items-center gap-2 text-sm font-bold"><CheckSquare className="h-4 w-4" />Official feature delivery plan</div><p className="feature-delivery-board-copy mt-1 text-[11px]">{tasks.length} detailed Spec-Kit task{tasks.length === 1 ? '' : 's'} from this feature’s <code>tasks.md</code> · {planCompletedCount} marked complete in the plan · {reviewedReceiptCount} Studio-reviewed receipt{reviewedReceiptCount === 1 ? '' : 's'} · {sourcePath || 'tasks.md'}</p><p className="feature-delivery-board-note mt-1 text-[10px]">This is the implementation authority for this feature, not a workspace task-board count.</p>{authorityLabel && <p className="feature-delivery-board-note mt-1 text-[10px] font-semibold">Authority: {authorityLabel}</p>}</div><div className="feature-delivery-board-tabs inline-flex rounded-lg border p-1 text-[11px]">{([['kanban', Columns3, 'Kanban'], ['matrix', Table2, 'Trace matrix'], ['source', Code, 'Source']] as const).map(([id, Icon, label]) => <button key={id} type="button" onClick={() => setView(id)} className={`feature-delivery-board-tab inline-flex items-center gap-1 rounded-md px-2.5 py-1.5 font-bold ${view === id ? 'feature-delivery-board-tab--active' : ''}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div></div>
    {view === 'kanban' && <div className="grid gap-3 p-4 xl:grid-cols-3">{columns.map((column) => <section key={column.id} className={`feature-delivery-board-column feature-delivery-board-column--${column.id} min-h-80 rounded-2xl border p-4`}><div className="feature-delivery-board-column-label mb-4 flex items-center justify-between text-xs font-bold"><span className="flex items-center gap-1.5">{column.icon}{column.label}</span><span className="feature-delivery-board-count rounded px-2 py-0.5">{column.tasks.length}</span></div><div className="space-y-3">{column.tasks.map((task) => <article key={task.id} className="feature-delivery-board-card rounded-xl border p-4 shadow-sm transition-all hover:-translate-y-0.5"><div className="flex items-center justify-between gap-2"><span className="feature-delivery-board-task-id font-mono text-[10px] font-bold">{task.id}</span>{task.requirementIds.length > 0 && <span className="feature-delivery-board-requirements rounded border px-1.5 py-0.5 text-[10px] font-medium">{task.requirementIds.join(', ')}</span>}</div><h4 className="feature-delivery-board-card-title mt-3 text-xs font-bold leading-relaxed">{task.title}</h4>{task.detail && <p className="feature-delivery-board-copy mt-2 line-clamp-3 text-[11px] leading-relaxed">{task.detail}</p>}<div className="feature-delivery-board-card-footer mt-3 flex items-center justify-between border-t pt-3 text-[10px]"><span className="feature-delivery-board-copy inline-flex items-center gap-1"><Clock3 className="h-3 w-3" />Feature task</span><span className={`feature-delivery-board-status feature-delivery-board-status--${column.id === 'active' ? 'active' : task.completionSource} rounded px-1.5 py-0.5`}>{column.id === 'active' ? 'Running locally' : task.completionSource === 'reviewed-receipt' ? 'Reviewed receipt' : task.completionSource === 'tasks-md' ? 'Marked in tasks.md' : 'Planned'}</span></div></article>)}{column.tasks.length === 0 && <div className="feature-delivery-board-empty rounded-xl border border-dashed p-6 text-center text-xs">{column.label === 'In progress' ? 'No local task is running.' : 'No tasks yet.'}</div>}</div></section>)}</div>}
    {view === 'matrix' && <div className="overflow-auto p-4"><table className="feature-delivery-board-matrix w-full text-left text-xs"><thead className="text-[10px] uppercase tracking-wider"><tr><th className="p-3">Task</th><th className="p-3">Requirement</th><th className="p-3">Completion evidence</th></tr></thead><tbody>{tasks.map((task) => { const isActive = !task.done && task.id === activeTaskId; const status = isActive ? 'active' : task.completionSource; return <tr key={task.id}><td className="p-3"><span className="feature-delivery-board-task-id font-mono">{task.id}</span><span className="feature-delivery-board-card-title ml-2">{task.title}</span></td><td className="feature-delivery-board-matrix-requirements p-3">{task.requirementIds.join(', ') || '—'}</td><td className="p-3"><span className={`feature-delivery-board-status feature-delivery-board-status--${status}`}>{isActive ? 'Running locally' : task.completionSource === 'reviewed-receipt' ? 'Studio-reviewed receipt' : task.completionSource === 'tasks-md' ? 'Marked complete in tasks.md' : 'Not completed'}</span></td></tr>; })}</tbody></table></div>}
    {view === 'source' && <pre className="feature-delivery-board-source max-h-80 overflow-auto whitespace-pre-wrap p-4 text-[10px] leading-relaxed">{content}</pre>}
  </div>;
}
