import React, { useState } from 'react';
import { CheckCircle2, Cpu, HardDrive, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import { SpecKitProject } from '../../types/speckit';
import { localAgentLabels } from '../../lib/agentAvailability';
import { getStudioSettings, saveStudioSettings, StudioSettings as Settings } from '../../lib/studioSettings';
import { SpecKitVersionSelector } from '../common/SpecKitVersionSelector';
import { THEME_PRESETS, useTheme } from '../../context/ThemeContext';

interface Props { project: SpecKitProject; onSelectVersion: (version: string) => void; onOpenWorkspace: () => void; }

export function StudioSettings({ project, onSelectVersion, onOpenWorkspace }: Props) {
  const [settings, setSettings] = useState<Settings>(() => getStudioSettings());
  const { theme, setTheme } = useTheme();
  const update = (partial: Partial<Settings>) => { const next = { ...settings, ...partial }; setSettings(next); saveStudioSettings(next); };
  const hasRepo = Boolean(project.importedRepo?.repoUrl);

  return <div className="mx-auto max-w-4xl space-y-6 pb-12">
    <header><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-cyan-400"><Settings2 className="h-4 w-4" />Studio settings</div><h1 className="mt-1 text-2xl font-bold text-zinc-100">Make Studio work your way—without changing the workflow</h1><p className="mt-2 max-w-2xl text-sm text-zinc-400">These preferences shape how Studio presents and runs work. Repository rules and Spec-Kit artifacts remain reviewable in the Feature Journey.</p></header>

    <section className="rounded-2xl border border-cyan-500/25 bg-cyan-500/5 p-5"><div className="flex gap-3"><div className="rounded-xl bg-cyan-500/15 p-2 text-cyan-300"><Cpu className="h-5 w-5" /></div><div><h2 className="font-bold text-zinc-100">Engine & workflow</h2><p className="mt-1 text-xs text-zinc-400">Spec-Kit Engine is always the preferred path when a compatible local agent is ready. Gemini is a fallback, not a replacement workflow.</p></div></div><div className="mt-4 grid gap-4 border-t border-cyan-500/15 pt-4 sm:grid-cols-2"><label className="text-xs font-semibold text-zinc-300">Preferred local agent<select value={settings.preferredAgent} onChange={(event) => update({ preferredAgent: event.target.value as Settings['preferredAgent'] })} className="mt-1.5 w-full rounded-xl border border-zinc-700 bg-zinc-950 p-3 text-zinc-100"><option value="auto">Auto-select best available</option>{Object.entries(localAgentLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><span className="mt-1 block text-[11px] font-normal text-zinc-500">If unavailable, Studio safely uses the next detected agent.</span></label><div className="space-y-2"><div className="flex items-start gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><span><strong className="text-xs text-zinc-200">Human approval stays on</strong><span className="mt-1 block text-[11px] text-zinc-500">The Engine can prepare a stage, but only you advance the Journey or apply repository changes.</span></span></div><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><input type="checkbox" checked={settings.showAdvancedTools} onChange={(event) => update({ showAdvancedTools: event.target.checked })} className="mt-0.5 accent-cyan-400" /><span><strong className="text-xs text-zinc-200">Show advanced tools</strong><span className="mt-1 block text-[11px] text-zinc-500">Show Repository Import in the Journey Map. You can turn it on whenever you need it.</span></span></label></div></div></section>

    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><div className="flex gap-3"><div className="rounded-xl bg-indigo-500/15 p-2 text-indigo-300"><Sparkles className="h-5 w-5" /></div><div><h2 className="font-bold text-zinc-100">Spec-Kit compatibility</h2><p className="mt-1 text-xs text-zinc-400">Choose the Studio target version for this feature workspace. The connected repository remains the source of truth for the installed CLI and integration.</p></div></div><div className="mt-4"><SpecKitVersionSelector currentVersion={project.version} onSelectVersion={onSelectVersion} variant="full" /></div></section>

    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><h2 className="font-bold text-zinc-100">Appearance</h2><p className="mt-1 text-xs text-zinc-400">Theme is a personal Studio preference and never changes repository files.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{THEME_PRESETS.map((preset) => <button type="button" key={preset.id} onClick={() => setTheme(preset.id)} className={`rounded-xl border p-3 text-left ${theme === preset.id ? 'border-cyan-400 bg-cyan-500/10' : 'border-zinc-800 bg-zinc-950 hover:border-zinc-700'}`}><div className="flex items-center justify-between"><strong className="text-xs text-zinc-100">{preset.name}</strong>{theme === preset.id && <CheckCircle2 className="h-4 w-4 text-cyan-300" />}</div><p className="mt-1 text-[11px] text-zinc-500">{preset.description}</p></button>)}</div></section>

    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-emerald-500/15 p-2 text-emerald-300"><HardDrive className="h-5 w-5" /></div><div><h2 className="font-bold text-zinc-100">Local connector & privacy</h2><p className="mt-1 text-xs text-zinc-400">Repository access and agent execution happen through the local connector. Pairing tokens are never saved in these settings.</p><p className="mt-2 text-[11px] text-zinc-500">{hasRepo ? `Connected: ${project.importedRepo?.repoName}` : 'No connected repository yet.'}</p></div></div><button type="button" onClick={onOpenWorkspace} className="shrink-0 rounded-lg border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-200 hover:bg-emerald-500/20">Open workspace</button></div></section>

    <p className="flex items-center gap-2 text-xs text-zinc-500"><ShieldCheck className="h-4 w-4 text-emerald-400" />Sensitive actions still require an explicit confirmation at the point of action.</p>
  </div>;
}
